version: '3.1'

services:
  chatroom:
    image: ababy/golang-dependency
    container_name: chatroom
    volumes:
    - .:/go/src/chatroom
    ports:
      - 9200:9200
    working_dir: /go/src/chatroom
    command: go run main.go
